// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRuZe0npmOpqE7VIjUYH8GbrXrftw0VNk',
    appId: '1:891461489081:web:3d3f92ee99ec39c58f2668',
    messagingSenderId: '891461489081',
    projectId: 'dino-9cf72',
    authDomain: 'dino-9cf72.firebaseapp.com',
    storageBucket: 'dino-9cf72.firebasestorage.app',
    measurementId: 'G-2GNV8XP3GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Q-d2F2MNiJFMg5_D_3GfT8c0owQImew',
    appId: '1:891461489081:android:5ae9939afdcd8af28f2668',
    messagingSenderId: '891461489081',
    projectId: 'dino-9cf72',
    storageBucket: 'dino-9cf72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2oWmUuqsJlsnhnErZz98hqNX9xD44MPM',
    appId: '1:891461489081:ios:aa108246f383c3c88f2668',
    messagingSenderId: '891461489081',
    projectId: 'dino-9cf72',
    storageBucket: 'dino-9cf72.firebasestorage.app',
    iosBundleId: 'com.example.apk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2oWmUuqsJlsnhnErZz98hqNX9xD44MPM',
    appId: '1:891461489081:ios:aa108246f383c3c88f2668',
    messagingSenderId: '891461489081',
    projectId: 'dino-9cf72',
    storageBucket: 'dino-9cf72.firebasestorage.app',
    iosBundleId: 'com.example.apk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRuZe0npmOpqE7VIjUYH8GbrXrftw0VNk',
    appId: '1:891461489081:web:0bc83271df49e3af8f2668',
    messagingSenderId: '891461489081',
    projectId: 'dino-9cf72',
    authDomain: 'dino-9cf72.firebaseapp.com',
    storageBucket: 'dino-9cf72.firebasestorage.app',
    measurementId: 'G-J3G0BXYHEH',
  );

}